name: BotcPlugin
version: ${project.version}
main: fr.cesi.botc.Botc
api-version: 1.20
softdepend: [voicechat]
commands:
  botc:
    description: Commande centrale du plugin Blood on the Clocktower
    usage: /botc <argument>